# Generated by Django 5.0.1 on 2024-01-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_game_comment_hotitem_play_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='source',
            field=models.TextField(default='BGG'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchlog',
            name='source',
            field=models.TextField(default='BGG'),
        ),
    ]
