# Generated by Django 5.0.1 on 2024-01-27 23:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_comment_source_searchlog_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='total_plays',
        ),
        migrations.RemoveField(
            model_name='user',
            name='game',
        ),
        migrations.RemoveField(
            model_name='user',
            name='times_played',
        ),
        migrations.AddField(
            model_name='play',
            name='play_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='play',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='games_played',
            field=models.ManyToManyField(through='data.Play', to='data.game'),
        ),
    ]
