# Generated by Django 5.0.1 on 2024-03-09 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_remove_play_total_plays_remove_user_game_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NounChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunks_data', models.JSONField()),
                ('version', models.IntegerField(unique=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.game')),
            ],
        ),
    ]
