# Generated by Django 5.0.1 on 2024-03-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_nounchunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nounchunk',
            name='version',
            field=models.IntegerField(),
        ),
    ]
