# Generated by Django 5.0.1 on 2024-03-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_rename_thread_thread_thread_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='data_posted',
            new_name='date_posted',
        ),
    ]
